/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkRouteImport } from './routes/_app.work'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppMyDayRouteImport } from './routes/_app.my-day'
import { Route as AppMecRouteImport } from './routes/_app.mec'
import { Route as AppKnowledgeRouteImport } from './routes/_app.knowledge'
import { Route as AppHelpRouteImport } from './routes/_app.help'
import { Route as AppAvailabilityRouteImport } from './routes/_app.availability'
import { Route as AppWorkTaskIdRouteImport } from './routes/_app.work.$taskId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkRoute = AppWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppMyDayRoute = AppMyDayRouteImport.update({
  id: '/my-day',
  path: '/my-day',
  getParentRoute: () => AppRoute,
} as any)
const AppMecRoute = AppMecRouteImport.update({
  id: '/mec',
  path: '/mec',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppAvailabilityRoute = AppAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkTaskIdRoute = AppWorkTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => AppWorkRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/availability': typeof AppAvailabilityRoute
  '/help': typeof AppHelpRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/mec': typeof AppMecRoute
  '/my-day': typeof AppMyDayRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/work': typeof AppWorkRouteWithChildren
  '/work/$taskId': typeof AppWorkTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/availability': typeof AppAvailabilityRoute
  '/help': typeof AppHelpRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/mec': typeof AppMecRoute
  '/my-day': typeof AppMyDayRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/work': typeof AppWorkRouteWithChildren
  '/work/$taskId': typeof AppWorkTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/availability': typeof AppAvailabilityRoute
  '/_app/help': typeof AppHelpRoute
  '/_app/knowledge': typeof AppKnowledgeRoute
  '/_app/mec': typeof AppMecRoute
  '/_app/my-day': typeof AppMyDayRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/work': typeof AppWorkRouteWithChildren
  '/_app/work/$taskId': typeof AppWorkTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/availability'
    | '/help'
    | '/knowledge'
    | '/mec'
    | '/my-day'
    | '/reports'
    | '/settings'
    | '/work'
    | '/work/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/availability'
    | '/help'
    | '/knowledge'
    | '/mec'
    | '/my-day'
    | '/reports'
    | '/settings'
    | '/work'
    | '/work/$taskId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_app/availability'
    | '/_app/help'
    | '/_app/knowledge'
    | '/_app/mec'
    | '/_app/my-day'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/work'
    | '/_app/work/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/work': {
      id: '/_app/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof AppWorkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-day': {
      id: '/_app/my-day'
      path: '/my-day'
      fullPath: '/my-day'
      preLoaderRoute: typeof AppMyDayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mec': {
      id: '/_app/mec'
      path: '/mec'
      fullPath: '/mec'
      preLoaderRoute: typeof AppMecRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge': {
      id: '/_app/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help': {
      id: '/_app/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/availability': {
      id: '/_app/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AppAvailabilityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/work/$taskId': {
      id: '/_app/work/$taskId'
      path: '/$taskId'
      fullPath: '/work/$taskId'
      preLoaderRoute: typeof AppWorkTaskIdRouteImport
      parentRoute: typeof AppWorkRoute
    }
  }
}

interface AppWorkRouteChildren {
  AppWorkTaskIdRoute: typeof AppWorkTaskIdRoute
}

const AppWorkRouteChildren: AppWorkRouteChildren = {
  AppWorkTaskIdRoute: AppWorkTaskIdRoute,
}

const AppWorkRouteWithChildren =
  AppWorkRoute._addFileChildren(AppWorkRouteChildren)

interface AppRouteChildren {
  AppAvailabilityRoute: typeof AppAvailabilityRoute
  AppHelpRoute: typeof AppHelpRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppMecRoute: typeof AppMecRoute
  AppMyDayRoute: typeof AppMyDayRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWorkRoute: typeof AppWorkRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAvailabilityRoute: AppAvailabilityRoute,
  AppHelpRoute: AppHelpRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppMecRoute: AppMecRoute,
  AppMyDayRoute: AppMyDayRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWorkRoute: AppWorkRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
